services:
  # =========================
  # MYSQL LOCAL
  # =========================
  mysql:
    image: mysql:8
    container_name: demopython-mysql
    profiles: ["local"]
    environment:
      MYSQL_DATABASE: ${DB_NAME:-demo}
      MYSQL_USER: ${DB_USER:-demo}
      MYSQL_PASSWORD: ${DB_PASSWORD:-demo}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpass}
    networks: [demo-net]
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p${DB_ROOT_PASSWORD:-rootpass} --silent"]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 20s

  # =======================
  # APP LOCAL (MySQL local)
  # ========================
  demo-python-local:
    build: .
    image: ${IMAGE_URI:-demo-python-local}
    container_name: demo-python-app-local
    profiles: ["local"]
    environment:
      DB_ENGINE: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ${DB_NAME:-demo}
      DB_USER: ${DB_USER:-demo}
      DB_PASSWORD: ${DB_PASSWORD:-demo}

      # opcional (tu app puede ignorarlo)
      DB_USE_SSL: "false"
    ports:
      - "${APP_PORT:-8082}:5000"
    depends_on:
      mysql:
        condition: service_healthy
    networks: [demo-net]
    restart: unless-stopped

  # =========================
  # APP REMOTO (MySQL RDS)
  # =========================
  demo-python-remote:
    image: "${IMAGE_URI?ERROR define IMAGE_URI for remote}"
    container_name: demo-python-app-remote
    profiles: ["remote"]
    environment:
      DB_ENGINE: mysql
      DB_HOST: ${DB_HOST:?DB_HOST required}
      DB_PORT: ${DB_PORT:-3306}
      DB_NAME: ${DB_NAME:-demo}
      DB_USER: ${DB_USER:?DB_USER required}
      DB_PASSWORD: ${DB_PASSWORD:?DB_PASSWORD required}

      # opcional: en RDS suele ser true
      DB_USE_SSL: ${DB_USE_SSL:-true}
    ports:
      - "${APP_PORT:-8082}:5000"
    networks: [demo-net]
    restart: unless-stopped

networks:
  demo-net:
    driver: bridge