# docker-compose para el despliegue en EC2
services:
  app:
    image: ${IMAGEN}          # se coge desde el workflow
    container_name: spring-app
    restart: always
    ports:
      - "80:8080"             # ajusta el puerto seg√∫n la app
    env_file:
      - .env.app              # archivo con variables de entorno de la app

